"""
    Build calt feature code from "*.code" glyph names.

    Works best to run on a UFO in a varfontprep folder, so it doesn't generate code for nonexisting glyphs.

    USAGE:

    python <path>/make-calt-fea-code.py "<path>/<source-font>.ufo"
"""

import sys
from fontParts.world import *

try:
    sourceUFO = sys.argv[1]
except IndexError:
    print("At least one arg required: path of UFO with code ligature glyphs")

font = OpenFont(sourceUFO, showInterface=False)

codeLigs = []

caltCode = ""

def makeCaltBlock(ligName):
    feaName = ligName.replace(".code","")
    ligSequence = feaName.replace("_","' ") + "'"
    firstChar = feaName.split("_")[0]
    lastChar = feaName.split("_")[-1]

    block = f"""\
lookup {feaName} {{
    ignore sub {firstChar} {ligSequence};
    ignore sub {ligSequence} {lastChar};
"""

    feaList = feaName.split("_")
    filler = "LIG"

    # create inner logic
    logic = ""

    for i in range(len(feaList) -1, -1, -1):
        logic += "    sub " + (f"{filler} " * i) + " ".join([feaList[i] + "'"] + feaList[i + 1:])

        logic += f" by {ligName};\n" if i == len(feaList) -1 else f" by {filler};\n"

    block += logic

    # end block
    block += f"""\
}} {feaName};
    """

    return block

for g in font:
    if ".code" in g.name and "_" in g.name and g.name not in font.lib["public.skipExportGlyphs"]:
        codeLigs.append(g.name)

font.close()

codeLigsSorted = sorted(codeLigs,key=lambda x: x.count('_'),reverse=True)

caltBlocks = ""
for lig in codeLigsSorted:
    caltBlocks += makeCaltBlock(lig) + "\n"

caltCode = f"""\
# generated by src/01-shell-scripts-for-sources/features/make-calt-fea-code.py
feature calt {{
{caltBlocks}\
}} calt;
"""

feaPath = "src/features/features/calt-generated--code_fonts_only.fea"
with open(feaPath, "w") as f:
    f.write(caltCode)

print(f"→ caltCode saved to {feaPath}")
