"""
	Build dlig feature code from "*.code" glyph names.

	USAGE:

	python <path>/make-dlig-fea-code.py "<path>/<source-font>.ufo"
"""

import sys
from fontParts.world import *

try:
    sourceUFO = sys.argv[1]
except IndexError:
    print("At least one arg required: path of UFO with code ligature glyphs")

font = OpenFont(sourceUFO, showInterface=False)

codeLigs = []

dligCode = ""

def makeDligBlock(ligName):
	feaName = ligName.replace(".code","")
	ligSequence = feaName.replace("_","' ") + "'"
	firstChar = feaName.split("_")[0]
	lastChar = feaName.split("_")[-1]
	block = f"""\
	lookup {feaName} {{
		ignore sub {firstChar} {ligSequence};
		ignore sub {ligSequence} {lastChar};
		sub {ligSequence} by {ligName};
	}} {feaName};
	"""
	return block

for g in font:
	if ".code" in g.name and "_" in g.name:
		codeLigs.append(g.name)

print(codeLigs)

font.close()


dligBlocks = ""
for lig in codeLigs:
	dligBlocks += makeDligBlock(lig) + "\n"

dligCode = f"""\
# generated by src/01-shell-scripts-for-sources/features/make-dlig-fea-code.py
feature dlig {{
	{dligBlocks}\
}} dlig;
"""

feaPath = "src/features/features/dlig-generated.fea"
with open(feaPath, "w") as f:
	f.write(dligCode)



print(dligCode)


# lookup exclam_equal_equal {
# 	ignore sub exclam exclam' equal' equal';
# 	ignore sub exclam' equal' equal' equal;
# 	sub exclam' equal' equal' by exclam_equal_equal.code;
# } exclam_equal_equal;
